# Generated by Django 3.1.6 on 2021-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='image',
            field=models.ImageField(default=2, upload_to='ProyectoWeb', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
